"""initial_schema

Revision ID: 7d9f160ca466
Revises: 
Create Date: 2026-05-05 09:05:57.959518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d9f160ca466'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False, comment='Stored PDF filename in Blob (e.g. uuid.pdf)'),
    sa.Column('original_name', sa.String(length=500), nullable=False, comment='Original uploaded image filename'),
    sa.Column('blob_url', sa.String(length=1000), nullable=False, comment='Full Azure Blob URL to the PDF'),
    sa.Column('blob_name', sa.String(length=500), nullable=False, comment='Blob object name within the container'),
    sa.Column('category', sa.Enum('Sales', 'Purchase', 'Inventory', 'HR', 'Finance', 'Legal', name='document_category'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'uploaded', 'failed', name='document_status'), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='Size in bytes of the original image'),
    sa.Column('pdf_size', sa.BigInteger(), nullable=True, comment='Size in bytes of the generated PDF'),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='Original image MIME type'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, comment='User-defined tags for search/filter'),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_name', sa.String(length=255), nullable=True, comment='Denormalised name for quick display'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blob_url')
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_at'), 'documents', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_id'), 'documents', ['uploaded_by_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('upload', 'view', 'download', 'delete', name='activity_action'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_name', sa.String(length=500), nullable=False, comment='Denormalised name in case document is deleted'),
    sa.Column('document_category', sa.Enum('Sales', 'Purchase', 'Inventory', 'HR', 'Finance', 'Legal', name='document_category'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_document_id'), 'activity_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_document_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_documents_uploaded_by_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_uploaded_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
